### PR TITLE
Add a heroku deploy button

### PR DESCRIPTION
**Pull request by bomb1e**
Added one and tested it on my heroku. Realised that this may not work well because `ENVIRONMENT` variables are required in the app.yaml before deploying

image

This is what I get. Assuming it's because the configs aren't set up

### CODE REVIEW

**Comment by kn9ts** [comment]
@bomb1e It should be a `POST` request. 

Refer to this: http://kn9ts.github.io/project-mulla/docs/deploy-heroku.html

Let me know if it helps.

**Comment by kn9ts** [comment]
Also could you use the documentation above to refactor the Heroku button for the perfect deployment. Thanks.

**Comment by bomb1e** [comment]
Checked out the docs. Awesome stuff!! :+1: 

Looking into the best way to go about this

**Comment by kn9ts** [comment]
Awesome. am glad it helped. Looking forward to your update. 😉

**Comment by kn9ts** [comment]
@bomb1e Any updates??? A deploy to Heroku button can come in handy...should I look into this myself or you're still up for the task?

**Pull request closed without merging**
