### PR TITLE
[Fixed #23] Fix all eslint syntax and style issues

### PR DESCRIPTION
**Pull request by gangachris**

### CODE REVIEW

**Comment by denzelwamburu** [comment]
@gangachris  @kn9ts Travis build seems to be failing, had you configured it?
Though it's a non issue.

**Comment by kn9ts** [comment]
@denzelwamburu I haven't yet. I'm still considering using it. My preference is `SemaphoreCI`

**Comment by denzelwamburu** [comment]
@kn9ts I haven't used before `SemaphoreCI` but i Travis works great with open source, you can give it a try :smile:

**Comment by denzelwamburu** [comment]
I have Created a Pull for Travis https://github.com/kn9ts/project-mulla/pull/29

**Pull request merged**
